name: lint

on:
  push:
    branches: [ test-lint ]

jobs:
  hello:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Lint Code
      run: |
        ls
        cd 2022-01-23-git-hooks
        make check-format
        make lint